#!/usr/bin/env python3
"""
AutoMD MCP Server - Automatic project documentation via MCP protocol
"""

import sys
from typing import Any
from pathlib import Path

from mcp.server.fastmcp import FastMCP

# Initialize FastMCP server
mcp = FastMCP("automd")


@mcp.tool()
async def init(project_path: str = ".") -> str:
    """Initialize AutoMD by creating .auto.md files in all directories.

    Args:
        project_path: Path to the project directory to scan (default: current directory)
    """
    try:
        # Validate project path
        if not isinstance(project_path, str):
            return "Error: project_path must be a string"
        
        if not project_path.strip():
            return "Error: project_path cannot be empty"
        
        project_root = Path(project_path).resolve()
        
        if not project_root.exists():
            return f"Error: Project path '{project_path}' does not exist"
        
        # For now, just create a simple .auto.md file in root
        auto_md_path = project_root / ".auto.md"
        
        content = f"""# AutoMD Documentation

## Project: {project_root.name}

**last_updated: {project_root.name}**

This directory contains AutoMD documentation.

### Files and Directories

This is a basic AutoMD file created during initialization.

---
*Generated by AutoMD*
"""
        
        with open(auto_md_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        return f"Successfully initialized AutoMD in '{project_root}'. Created .auto.md file."
        
    except Exception as e:
        return f"Error initializing AutoMD: {str(e)}"


@mcp.tool()
async def update(project_path: str = ".") -> str:
    """Update all .auto.md files by rescanning the project.

    Args:
        project_path: Path to the project directory to update (default: current directory)
    """
    try:
        # Validate project path
        if not isinstance(project_path, str):
            return "Error: project_path must be a string"
        
        if not project_path.strip():
            return "Error: project_path cannot be empty"
        
        project_root = Path(project_path).resolve()
        
        if not project_root.exists():
            return f"Error: Project path '{project_path}' does not exist"
        
        # For now, just update timestamp in existing .auto.md files
        auto_md_files = list(project_root.rglob(".auto.md"))
        
        if not auto_md_files:
            return "No .auto.md files found. Run init first."
        
        updated_count = 0
        for auto_md_path in auto_md_files:
            try:
                # Read existing content
                with open(auto_md_path, 'r', encoding='utf-8') as f:
                    content = f.read()
                
                # Simple update - just add a timestamp
                from datetime import datetime
                timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                
                if "Last updated:" in content:
                    # Replace existing timestamp
                    import re
                    content = re.sub(r'Last updated:.*', f'Last updated: {timestamp}', content)
                else:
                    # Add timestamp
                    content += f"\n\nLast updated: {timestamp}"
                
                # Write back
                with open(auto_md_path, 'w', encoding='utf-8') as f:
                    f.write(content)
                
                updated_count += 1
                
            except Exception as e:
                return f"Error updating {auto_md_path}: {str(e)}"
        
        return f"Successfully updated {updated_count} .auto.md files."
        
    except Exception as e:
        return f"Error updating AutoMD: {str(e)}"


def main():
    """Main entry point"""
    # Run the server with stdio transport
    mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
